---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - answerfile_attach_tnp_to_cluster_9x.yml
  
  tasks:
    - name: Create edge transport nodes (async)
      vmware.ansible_for_nsxt.nsxt_transport_nodes:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        display_name: "{{ item.display_name }}"
        description: "Edge transport node ansible"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{ item.host_switches }}"
        node_deployment_info: "{{ item.node_deployment_info }}"
        state: present
      with_items: "{{ edge_transport_nodes }}"


