---
- hosts: 127.0.0.1
  connection: local
  vars:
    nsx: "192.168.50.54"
    user: "admin"
    password: "VMware1!VMware1!"
    
  tasks:
    - name: Create T0
      vmware.ansible_for_nsxt.nsxt_logical_routers:
        hostname: "{{ nsx }}"
        username: "{{ user }}"
        password: "{{ password }}"
        validate_certs: False
        state: "{{ state }}"
        display_name: "myTier-0"
        edge_cluster_name: "Eedge-cluster-1"
        router_type: "TIER0"
        high_availability_mode: "ACTIVE_STANDBY"
