            # Route Redistribution - Multiple Rules Approach
            route_redistribution_config:
              bgp_enabled: true
              redistribution_rules:
                # Rule 1: Tier0 specific routes
                - name: "tier0-routes"
                  route_redistribution_types: 
                    - "TIER0_STATIC"
                    - "TIER0_CONNECTED"
                    - "TIER0_EXTERNAL_INTERFACE"
                    - "TIER0_LOOPBACK_INTERFACE"
                    - "TIER0_SEGMENT"
                    - "TIER0_ROUTER_LINK"
                    - "TIER0_SERVICE_INTERFACE"
                    - "TIER0_DNS_FORWARDER_IP"
                    - "TIER0_IPSEC_LOCAL_IP"
                    - "TIER0_NAT"
                    - "TIER0_EVPN_TEP_IP"
                
                # Rule 2: Tier1 advertised routes
                - name: "tier1-routes"
                  route_redistribution_types:
                    - "TIER1_STATIC"
                    - "TIER1_CONNECTED"
                    - "TIER1_NAT"
                    - "TIER1_LB_VIP"
                    - "TIER1_LB_SNAT"
                    - "TIER1_DNS_FORWARDER_IP"
                    - "TIER1_SERVICE_INTERFACE"
                    - "TIER1_SEGMENT"
                    - "TIER1_IPSEC_LOCAL_ENDPOINT"