hostname: "10.192.254.207"
username: "admin"
password: "Admin!23Admin"
validate_certs: False

edge_transport_nodes:
- display_name: EdgeTN1
  host_switches:
  - host_switch_profiles:
    - name: edge.profile
      type: UplinkHostSwitchProfile
    host_switch_name: nsxHostSwitch
    host_switch_mode: STANDARD
    pnics:
    - device_name: "fp-eth0"
      uplink_name: "uplink-1"
    ip_assignment_spec:
      resource_type: StaticIpPoolSpec
      ip_pool_name: "IPPool-IPV4-1"
    transport_zone_endpoints:
    - transport_zone_name: "nsx-overlay-transportzone"
  node_deployment_info:
    resource_type: "EdgeNode"
    display_name: "EdgeTN1"
    deployment_type: "VIRTUAL_MACHINE"
    deployment_config:
      form_factor: "SMALL"
      node_user_settings:
        cli_username: "admin"
        cli_password: "Admin!23Admin"
        root_password: "Admin!23Admin"
      vm_deployment_config:
        ipv4_assignment_enabled: true
        management_port_subnets:
          - ip_addresses:
              - "192.168.50.55"
            prefix_length: 24
        default_gateway_addresses:
          - "192.168.50.53"
        placement_type: VsphereDeploymentConfig
        vc_name: "vc52"
        vc_username: "administrator@vsphere.local"
        vc_password:  "VMware1!VMware1!"
        data_networks:
        - segment-vlan-trunk
        - segment-vlan-trunk
        - segment-vlan-trunk
        management_network:  "vds.v0"
        compute: "c"
        storage: "nfs1"
        host: "192.168.50.11"
    node_settings:
      allow_ssh_root_login: true
      enable_ssh: true
      hostname: "corp.internal"