---
- hosts: 127.0.0.1
  connection: local
  vars:
    hostname: "192.168.50.40"
    username: "admin"
    password: "VMware1@VMware1@"
    validate_certs: false

  tasks:
    - name: Create Edge Cluster and Add Member Node
      vmware.ansible_for_nsxt.nsxt_edge_clusters:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "edge-cluster-01"
        state: present
        members:
          - transport_node_name: "edge1"