- name: Setup vSphere Environment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Datacenter
      vmware.vmware.datacenter:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter_name: "DC1"
        state: present
        validate_certs: false

    - name: Create Cluster
      vmware.vmware.cluster:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "DC1"
        cluster: "Cluster1"
        state: present
        validate_certs: false