---
- hosts: localhost
  tasks:
    - name: esx.uplink.profile
      vmware.ansible_for_nsxt.nsxt_uplink_profiles:
        hostname: "192.168.50.54"
        username: "admin"
        password: "VMware1!VMware1!"
        validate_certs: false
        display_name: "esx.uplink.profile"
        transport_vlan: 116
        resource_type: "UplinkHostSwitchProfile"  # Added quotes
        teaming:
          active_list:
            - uplink_name: "uplink-1"
              uplink_type: "PNIC"
          standby_list:
            - uplink_name: "uplink-2"
              uplink_type: "PNIC"
          policy: "FAILOVER_ORDER"
        state: "present"

    - name: edge.uplink.profile
      vmware.ansible_for_nsxt.nsxt_uplink_profiles:
        hostname: "192.168.50.54"
        username: "admin"
        password: "VMware1!VMware1!"
        validate_certs: false
        display_name: "edge.uplink.profile"
        mtu: 1700
        transport_vlan: 116
        resource_type: "UplinkHostSwitchProfile"  # Added quotes
        teaming:
          active_list:
            - uplink_name: "uplink-1"
              uplink_type: "PNIC"
          # standby_list:
          #   - uplink_name: "uplink-2"
          #     uplink_type: "PNIC"
          policy: "FAILOVER_ORDER"
        state: "present"