# deploy_nsx_cluster_vars.yml
---
nsx_username: "admin"
nsx_password: "VMware1!VMware1!"
validate_certs: false

nsx_ova_path: "/root/tonjiak/"
nsx_ova: "nsx-unified-appliance-4.2.0.0.0.24105821.ova"

domain: "corp.internal"
netmask: "255.255.255.0"
gateway: "192.168.50.53"
dns_server: "192.168.50.53"
ntp_server: "192.168.50.53"

nsx_node1:
  hostname: "nsx61.corp.internal"
  mgmt_ip: "192.168.50.61"
  datacenter: "Datacenter"
  cluster: "cl1"
  datastore: "sata4b"
  portgroup: "VM Network"

compute_manager:
  mgmt_ip: "192.168.50.8"
  username: "administrator@vsphere.local"
  password: "VMware1!VMware1!"
  
