# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to test IP Pool
#
- hosts: localhost
  tasks:
    - name: create IP Pool
      vmware.ansible_for_nsxt.nsxt_policy_ip_pool:
        hostname: "192.168.50.54"
        username: "admin"
        password: "VMware1!VMware1!"
        validate_certs: false
        display_name: ippool
        state: "present"
        pool_static_subnets:
          - id: ip-static-subnet-1
            state: present
            allocation_ranges:
              - start: '192.168.116.10'
                end: '192.168.116.20'
              - start: '192.168.116.30'
                end: '192.168.116.40'
            cidr: '192.168.116.0/26'
