---
- hosts: 127.0.0.1
  connection: local
  become: yes
#need to deploy to vcenter
#documentation is trash, so the blog is trash https://blogs.vmware.com/networkvirtualization/2019/06/ansible-nsx-t-deployment.html/
#ansible doc for this trash is here https://ansible-for-nsxt-docs.readthedocs.io/en/latest/nsxt/nsxt_deploy_ova_module.html#parameter-path_to_ova
#use the ovftool to extract the ova to ovf and see the keys needed. 
# eg. ./ovftool/ovftool --allowExtraConfig ./nsx-unified-appliance-4.2.0.0.0.241058
  tasks:
    - name: deploy NSX Manager OVA
      vmware.ansible_for_nsxt.nsxt_deploy_ova:
        ovftool_path: "/root/ovftool"
        datacenter: "Datacenter"
        datastore: "nvme2"
        portgroup: "VM Network"
        cluster: "cc"
        vmname: "nsx54"
        hostname: "nsx54"
        dns_server: "192.168.50.53"
        dns_domain: "corp.internal"
        ntp_server: "192.168.50.53"
        gateway: "192.168.50.53"
        ip_address: "192.168.50.54"
        netmask: "255.255.255.0"
        admin_password: "VMware1!VMware1!"
        cli_password: "VMware1!VMware1!"
        path_to_ova: "/root"
        ova_file: "nsx-unified-appliance-4.2.0.0.0.24105821.ova"
        vcenter: "192.168.50.52"
        vcenter_user: "administrator@vsphere.local"
        vcenter_passwd: "VMware1!VMware1!"
        deployment_size: "medium"
        role: "NSX Manager"
    # - name: Check manager status
    #   vmware.ansible_for_nsxt.nsxt_manager_status:
    #       username: "admin"
    #       password: "VMware1!VMware1!"
    #       validate_certs: false
    #       wait_time: 50